### PR TITLE
Test against Django 1.11

### PR DESCRIPTION
**Pull request by vstoykov**
Modify travis and tox config files to include Django from 1.8 to 1.11 (included)

### CODE REVIEW

**Comment by ornoone** [comment]
LGTM. this should be merged along with a README.rst update of requirments.

**Comment by vstoykov** [comment]
Do you want from me to change the README?

One more thing is there some problem with travis because I don't see build status of my PR?

**Comment by ornoone** [comment]
If you can update the README rigth now, it can be cool. I will inspect the problem with travis.

**Comment by ornoone** [comment]
it seem travis build has failed because of bad version matrix. django 1.10+ does not support python 3.4-

**Comment by vstoykov** [comment]
Ok I will update my PR

**Comment by vstoykov** [comment]
In the README there was `Django >= 1.8` which implicitly include Django 1.11. Nevertheless I updated it to explicitly state which versions of Django are supported.

**Comment by ornoone** [comment]
great job @vstoykov. thanks for the PR. I asked the current maintainer of the repo to merge this. he is really busy ATM, but I hope this will be done soon.

**Pull request merged**
