### PR TITLE
Add Django 2 support, bump to v1.0.1

### PR DESCRIPTION
**Pull request by Andrey-Skvortsov**
* Add Django 2 compatibility
 * Bump to v1.0.1 (may be ready to move from alpha?) Also it needs to bump as some changes not in PyPi now.
 * Add function based field (would be useful when you need not a fix raw value but dynamically calculated, e.g. to join with language data in current active language)

### CODE REVIEW

**Review by ornoone — APPROVED** [review]
look good. nice work and IC config.

**Comment by ornoone** [comment]
@Andrey-Skvortsov do you want to write a small example in the doc for your ``FunctionBasedFieldValue`` before I merge and publish in pypi?

**Comment by Andrey-Skvortsov** [comment]
@ornoone Added an example for `FunctionBasedFieldValue`

**Comment by Andrey-Skvortsov** [comment]
@ornoone It's ready to merge and publish

**Review by ornoone — APPROVED** [review]
LGTM

**Comment by ornoone** [comment]
@tomlemeuch  can you upload it to pypi ? it seem the pypi package owner is Onysos.

**Comment by shun-liang** [comment]
@ornoone @tomlemeuch I am interested about when there will be a release based on this commit. Can I ask for an ETA? Many thanks.

**Comment by tohugaby** [comment]
**django-composite-foreignkey 1.01** uploaded on pypi.
@Andrey-Skvortsov thank you for your PR.

**Pull request merged**
