### PR TITLE
for django 2.0

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
for issue #3

### CODE REVIEW

**Comment by vstoykov** [comment]
Probably the suggestion made by @ornoone in #3 is better

**Comment by h4ck3rm1k3** [comment]
Fine with me.

**Comment by vstoykov** [comment]
I mean you can update your PR, because there is no PR from anybody to fix this.

**Comment by h4ck3rm1k3** [comment]
ok, well I dont need this right now. I am moving to golang from python for speed.

**Pull request closed without merging**
